[phases.setup]
nixPkgs = ["bun"]

[phases.install]
cmds = ["echo 'Monorepo detected - individual services will be built from their directories'"]

[phases.build]
cmds = ["echo 'Monorepo detected - services will be built individually'"]

[start]
cmd = "echo 'This is a monorepo - individual services should be deployed separately'"
