services:
  - type: web
    name: rashomon-api
    runtime: docker
    plan: free
    dockerfilePath: ./api/Dockerfile
    dockerContext: ./api
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: GOOGLE_CLOUD_VISION_API_KEY
        sync: false
    healthCheckPath: /

  - type: web
    name: rashomon-2
    runtime: docker
    plan: free
    dockerfilePath: ./app/Dockerfile
    dockerContext: ./app
    envVars:
      - key: NEXT_PUBLIC_SUPABASE_URL
        sync: false
      - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        sync: false
      - key: NEXT_PUBLIC_API_URL
        value: https://rashomon.onrender.com
    healthCheckPath: /
