[build]
builder = "nixpacks"

[deploy]
startCommand = "bun run index.ts"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[env]
PORT = "3001"
NODE_ENV = "production"
